default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: gen-swagger
        name: Generate Swagger docs
        entry: swag init -g internal/command/server/command.go -o gen/swagger --parseDependencyLevel 3 --parseInternal
        language: system
        pass_filenames: false
        files: (internal/command/server/[^/]+$|^go\.mod$)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb=512"]

  - repo: https://github.com/lwmacct/251211-pre-commit
    rev: v1.0.2
    hooks:
      - id: prettier
      - id: mc-mdtoc
      - id: golangci-lint
      - id: config-sync
