// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/lwmacct/260103-ddd-settings-bc"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取按 Category → Group → Settings 层级组织的配置数据，用于前端动态渲染设置页面。支持按分类过滤（懒加载）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "配置列表",
                "parameters": [
                    {
                        "type": "string",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "配置列表（层级结构）",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-array_setting_SettingsCategoryDTO"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "分类不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员创建新的系统配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "创建配置",
                "parameters": [
                    {
                        "description": "配置信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "配置创建成功",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-setting_SettingDTO"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/settings/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员批量更新多个系统配置项的值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "批量更新配置",
                "parameters": [
                    {
                        "description": "配置列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.BatchUpdateSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量更新成功",
                        "schema": {
                            "$ref": "#/definitions/response.EmptyResponse"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/settings/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取所有配置分类，按排序权重升序排列",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "配置分类列表",
                "responses": {
                    "200": {
                        "description": "分类列表",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-array_setting_CategoryDTO"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员创建新的配置分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "创建配置分类",
                "parameters": [
                    {
                        "description": "分类信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "分类创建成功",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-setting_CategoryDTO"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/settings/categories/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 ID 获取配置分类详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "配置分类详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分类详情",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-setting_CategoryDTO"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "分类不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新指定配置分类的信息（Key 不可修改）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "更新配置分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "分类更新成功",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-setting_CategoryDTO"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "分类不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员删除指定的配置分类（如有关联配置项则拒绝删除）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "删除配置分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "分类删除成功"
                    },
                    "400": {
                        "description": "存在关联配置项",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "分类不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/admin/settings/{key}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据配置键获取配置详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "配置详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置键",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "配置详情",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-setting_SettingDTO"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新指定配置项的值和标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "更新配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置键",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateSettingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "配置更新成功",
                        "schema": {
                            "$ref": "#/definitions/response.DataResponse-setting_SettingDTO"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员删除指定的系统配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "删除配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "配置键",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "配置删除成功"
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "权限不足",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "配置不存在",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.BatchUpdateSettingsRequest": {
            "type": "object",
            "required": [
                "settings"
            ],
            "properties": {
                "settings": {
                    "description": "至少需要一个设置项",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "required": [
                            "key"
                        ],
                        "properties": {
                            "key": {
                                "type": "string"
                            },
                            "value": {
                                "description": "JSONB 原生值"
                            }
                        }
                    }
                }
            }
        },
        "handler.CreateCategoryRequest": {
            "type": "object",
            "required": [
                "key",
                "label"
            ],
            "properties": {
                "icon": {
                    "type": "string",
                    "example": "mdi-cog"
                },
                "key": {
                    "type": "string",
                    "example": "custom"
                },
                "label": {
                    "type": "string",
                    "example": "自定义配置"
                },
                "order": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "handler.CreateSettingRequest": {
            "type": "object",
            "required": [
                "category_id",
                "default_value",
                "key"
            ],
            "properties": {
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "default_value": {},
                "group": {
                    "type": "string",
                    "example": "basic"
                },
                "key": {
                    "type": "string",
                    "example": "site_name"
                },
                "label": {
                    "type": "string",
                    "example": "网站名称"
                },
                "order": {
                    "type": "integer",
                    "example": 0
                },
                "ui_config": {
                    "type": "string",
                    "example": "{}"
                },
                "value_type": {
                    "type": "string",
                    "example": "string"
                }
            }
        },
        "handler.UpdateCategoryRequest": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string",
                    "example": "mdi-settings"
                },
                "label": {
                    "type": "string",
                    "example": "更新后的标签"
                },
                "order": {
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "handler.UpdateSettingRequest": {
            "type": "object",
            "properties": {
                "default_value": {},
                "label": {
                    "type": "string",
                    "example": "更新后的标签"
                },
                "order": {
                    "type": "integer"
                },
                "ui_config": {
                    "type": "string"
                }
            }
        },
        "response.DataResponse-array_setting_CategoryDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP 状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/setting.CategoryDTO"
                    }
                },
                "error": {
                    "description": "错误详情（仅失败时）"
                },
                "message": {
                    "description": "消息描述",
                    "type": "string"
                }
            }
        },
        "response.DataResponse-array_setting_SettingsCategoryDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP 状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/setting.SettingsCategoryDTO"
                    }
                },
                "error": {
                    "description": "错误详情（仅失败时）"
                },
                "message": {
                    "description": "消息描述",
                    "type": "string"
                }
            }
        },
        "response.DataResponse-setting_CategoryDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP 状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/setting.CategoryDTO"
                        }
                    ]
                },
                "error": {
                    "description": "错误详情（仅失败时）"
                },
                "message": {
                    "description": "消息描述",
                    "type": "string"
                }
            }
        },
        "response.DataResponse-setting_SettingDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP 状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/setting.SettingDTO"
                        }
                    ]
                },
                "error": {
                    "description": "错误详情（仅失败时）"
                },
                "message": {
                    "description": "消息描述",
                    "type": "string"
                }
            }
        },
        "response.EmptyResponse": {
            "description": "空响应格式",
            "type": "object"
        },
        "response.ErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务错误码（小写下划线）",
                    "type": "string"
                },
                "details": {
                    "description": "额外详情（如验证错误列表）"
                },
                "message": {
                    "description": "错误消息",
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/response.ErrorDetail"
                }
            }
        },
        "setting.CategoryDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "setting.DependsOnConfigDTO": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "operator": {
                    "description": "eq, ne, gt, lt（默认 eq）",
                    "type": "string"
                },
                "value": {}
            }
        },
        "setting.SelectOptionDTO": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "setting.SettingDTO": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "configurable_at": {
                    "description": "最大可配置级别：system | org | team | user",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "default_value": {
                    "description": "JSONB 原生值"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "input_type": {
                    "description": "控件类型",
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "ui_config": {
                    "description": "hint/options/depends_on",
                    "allOf": [
                        {
                            "$ref": "#/definitions/setting.UIConfigDTO"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "validation": {
                    "description": "JSON Logic 规则"
                },
                "value_type": {
                    "type": "string"
                },
                "visible_at": {
                    "description": "最小可见级别：system | org | team | user",
                    "type": "string"
                }
            }
        },
        "setting.SettingsCategoryDTO": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/setting.SettingsGroupDTO"
                    }
                },
                "icon": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "setting.SettingsGroupDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "分组名称（如 \"基本设置\"）",
                    "type": "string"
                },
                "settings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/setting.SettingsItemDTO"
                    }
                }
            }
        },
        "setting.SettingsItemDTO": {
            "type": "object",
            "properties": {
                "configurable_at": {
                    "description": "最大可配置级别",
                    "type": "string"
                },
                "default_value": {
                    "description": "系统默认值"
                },
                "input_type": {
                    "description": "控件类型",
                    "type": "string"
                },
                "is_customized": {
                    "description": "是否用户自定义",
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "ui_config": {
                    "description": "hint/options/depends_on",
                    "allOf": [
                        {
                            "$ref": "#/definitions/setting.UIConfigDTO"
                        }
                    ]
                },
                "validation": {
                    "description": "JSON Logic 规则"
                },
                "value": {
                    "description": "实际生效值"
                },
                "value_type": {
                    "type": "string"
                },
                "visible_at": {
                    "description": "最小可见级别",
                    "type": "string"
                }
            }
        },
        "setting.UIConfigDTO": {
            "type": "object",
            "properties": {
                "depends_on": {
                    "description": "依赖关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/setting.DependsOnConfigDTO"
                        }
                    ]
                },
                "hint": {
                    "description": "输入提示",
                    "type": "string"
                },
                "options": {
                    "description": "下拉选项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/setting.SelectOptionDTO"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Settings Bounded Context API",
	Description:      "基于 DDD + CQRS 架构的配置管理模块",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
